name: On push trunk

on:
  push:
    branches:
      - 'trunk'
    paths-ignore:
      - 'app/package.json'
      - 'app/package-lock.json'
      - 'api/api.csproj'

env:
  NODE_VERSION: 14.17.3
  REPOSITORY: ruluzor/odeslad-blog
  AZURE_WEBAPP_NAME: odeslad-blog-app
  AZURE_WEBAPP_PACKAGE_PATH: './app/dist/app'
  AZURE_WEBAPI_NAME: odeslad-blog-api
  AZURE_WEBAPI_PACKAGE_PATH: './api/api/dist/'

jobs:
  run-scripts:
    name: Run scripts
    runs-on: ubuntu-latest
    steps:

    - name: Branch protection OFF
      uses: octokit/request-action@v2.x
      with:
        route: PUT /repos/:repository/branches/trunk/protection
        repository: ${{ github.repository }}
        required_status_checks: |
          null
        enforce_admins: |
          null
        required_pull_request_reviews: |
          null
        restrictions: |
          null
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_ACTION }}

    - name: Checkout files
      uses: actions/checkout@v2
      with:
        repository: ${{ env.REPOSITORY }}
        ref: trunk
        token: ${{ secrets.TOKEN_ACTION }}

    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Get current version environment
      run: |
        bash -c "node ./current_version.js '${{ github.event.head_commit.message }}' current_version >> $GITHUB_ENV"
        bash -c "node ./current_version.js '${{ github.event.head_commit.message }}' version_fragment >> $GITHUB_ENV"
    - name: Bump version
      id: bump_version
      uses: christian-draeger/increment-semantic-version@1.0.3
      with:
        current-version: ${{ env.current_version }}
        version-fragment: ${{ env.version_fragment }}

    - name: Update version
      run: |
        npm install --save xml-js
        npm install --save xml2js
        node ./bump_version.js ${{ steps.bump_version.outputs.next-version }}
    - name: Launch commit
      uses: EndBug/add-and-commit@v8
      with:
        author_name: CI
        message: "New SNAPSHOT: v${{ steps.bump_version.outputs.next-version }}"

    - name: Branch protection ON
      uses: octokit/request-action@v2.x
      with:
        route: PUT /repos/:repository/branches/trunk/protection
        repository: ${{ github.repository }}
        required_status_checks: |
          null
        enforce_admins: |
          true
        required_pull_request_reviews: |
          required_approving_review_count: 0
        restrictions: |
          null
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_ACTION }}

  deploy-app:
    name: Deploy app
    needs: run-scripts
    runs-on: ubuntu-latest
    steps:

    - name: Checkout files
      uses: actions/checkout@v2

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install packages
      working-directory: ./app
      run: npm ci

    - name: Build app
      working-directory: ./app
      run: npm run build --if-present

    - name: Run tests
      working-directory: ./app
      run: npm run test --if-present

    - name: Deploy to Azure
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_SETTINGS }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy-api:
    name: Deploy api
    needs: run-scripts
    runs-on: ubuntu-latest
    steps:

    - name: Checkout files
      uses: actions/checkout@v2

    - name: Setup .NET api
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies api
      working-directory: ./api/api
      run: dotnet restore

    - name: Build api
      working-directory: ./api/api
      run: dotnet build --configuration Release

    - name: Run tests api
      working-directory: ./api/tests
      run: dotnet test --no-build --verbosity normal

    - name: Publish api
      working-directory: ./api/api
      run: dotnet publish --configuration Release --framework net6.0 --self-contained false -o ./dist

    - name: Deploy to Azure
      id: deploy-to-webapi
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPI_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPI_PUBLISH_SETTINGS }}
        package: ${{ env.AZURE_WEBAPI_PACKAGE_PATH }}